server:
  port: 8080
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root123
  dataname: shopdevgo
  maxIdleConnections: 10
  maxOpenConnections: 100
  connectionsMaxLifetime: 3600
logger:
  level: debug
  filename: ./logs/dev.xxx.log
  maxSize: 500
  maxBackups: 5
  maxAge: 30